# Generated by Django 2.1.1 on 2018-11-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='sort_number',
            field=models.CharField(max_length=50, verbose_name='Порядковый номер'),
        ),
    ]
