# Generated by Django 2.1.1 on 2018-10-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, verbose_name='Название')),
                ('is_finished', models.BooleanField(verbose_name='Игра завершена')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100, verbose_name='идентефикатор игрока')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_count', models.IntegerField(verbose_name='Попытки')),
                ('game_creater', models.BooleanField(verbose_name='Создатель игры')),
                ('game_finished', models.BooleanField(verbose_name='Завершил игру')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='id игры')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player', verbose_name='id игрока')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(related_name='game', to='game.Player', verbose_name='Игрок'),
        ),
    ]
